### PR TITLE
Fix[#21]: Resolve badge color and sync issues in popup UI

### LINKED ISSUE #21: Badge sync delay and color inconsistency in popup UI
### Description

There is a noticeable delay when syncing the badge with the timer, especially during the initial seconds. Additionally, the badge color does not consistently reflect the timer state (e.g., delay or active). These issues affect both the visual consistency and UX of the extension.
We also need to revise the popup UI's badge design to better align with the overall aesthetic of the extension.

### Todo

- [ ] Investigate and resolve badge update delay during the initial countdown
- [ ] Fix inconsistent badge color logic
- [ ] Redesign badge style for better clarity and visual alignment
- [ ] Add test case for badge sync and visual consistency
- [ ] Update relevant UI and badge rendering logic

### ETC

This issue is especially noticeable when using the "preset" timer feature.
Consider matching badge colors to Bootstrap semantic colors (primary, warning, danger) for clarity.
Screenshots or recordings can help verify UI improvements once applied.

### PR DESCRIPTION
**Pull request by YuSoeun**
## 📌 Summary

Improved badge design and logic for delayed time  
This PR fixes badge color inconsistencies and improves how the badge reflects delay and elapsed time.  
Also includes updates to the issue description and todos for clarity.

---

## ✅ Changes

- [x] Fix: Bug fix or patch
- [x] Docs: Updated related issue description

**Details:**
- Fixed badge color inconsistency when delay starts (`popup.js`)
- Corrected badge color for elapsed time display (`background.js`)
- Improved badge rendering logic for better UI clarity
- Fixed minor errors when reopening popup and restarting timer
- Updated issue #21 with refined description and updated todo items

---

## 🔗 Related Issue

Closes #21

---

## 💬 Additional Notes

- Make sure to test the timer by starting, resetting, and reopening the popup multiple times  
- Check badge color for both "delay" and "elapsed" states  
- Confirm console is clean after popup reopen  
- Badge colors now match Bootstrap-style semantic colors for better UX clarity

### CODE REVIEW

File: popup.js [hunk 1]
```diff
@@ -663,7 +778,7 @@ function updateUIFromStatus(remaining, delay, totalSeconds) {
         elements.elapsed.style.color = 'var(--danger-color)'; // 지연 상태일 때는 분홍색으로 변경
       } else {
         elements.elapsed.textContent = formatTime(remaining);
-        elements.elapsed.style.color = 'var(--primary-color)'; // 정상 상태일 때는 원래 색상으로 복원
+        elements.elapsed.style.color = 'var(--text-primary)'; // 정상 상태일 때는 원래 색상으로 복원
```
Comment (YuSoeun) [inline popup.js:781]: Kept as-is for design reasons: --text-primary reflects the default/neutral state, and --primary-color is used for more prominent or alert visuals.
